### ISSUE TITLE
Why did you redo so much code?

### ISSUE THREAD

**Issue by thejh** [jdeal/doctor#1]
(not an issue, but couldn't quickly find another way to contact you)

Why did you redo so much code? Particularily JS parsing... [uglifyjs](https://github.com/mishoo/UglifyJS) already does a pretty good job at it (you get a nicer AST with my lib https://github.com/thejh/node-astjourney ).

**Comment by thejh** [comment]
Also, your code looks like it would have a huge benefit from streamlinejs. Just saying.

**Comment by bsgbryan** [comment]
The specific reason for this project was uglifiy's lackluster support for
comments in js. We have very specific needs around this in our current
project. The initial idea was to augment ulgify to expose the functionality
we need. This was not feasible, however.

On Thu, Jan 5, 2012 at 11:03 AM, Jann Horn <
reply@reply.github.com

> wrote:
> 
> (not an issue, but couldn't quickly find another way to contact you)
> 
> Why did you redo so much code? Particularily JS parsing... [uglifyjs](https://github.com/mishoo/UglifyJS) already does a pretty good job at it
> (you get a nicer AST with my lib https://github.com/thejh/node-astjourney).
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jdeal/doctor/issues/1

## 

For science

**Comment by jdeal** [comment]
I think Bryan said it well enough, but I'll just elaborate.

Uglify is not friendly to comments. (I want the code to generate the documentation, but you still at least have to use comments for descriptions.) Even its own readme explains this. I tried with ridiculous effort to make it work, but after a couple weeks, I gave up. I was able to get PEG.js to give me a comment-friendly AST in a few hours. Enough said.

Uglify also doesn't make a very nice AST in general, and yes, your module helps, but I started working on doctor before you announced your module.

As far as streamline, that's subjective. (Although I'm sure Bruno would disagree.) Most of the ugliness in my code is due to node.js's damned synchronous require. I wrote a lot of nice asynchronous code with the async library, and then I had to rip it all out because I wanted doctor to be able to run behind a require. See my discussion with Bruno on the node.js mailing list about this. Streamline cannot help. Nor can fibers.
