### ISSUE TITLE
Function as argument documentation

### ISSUE THREAD

**Issue by alexstrat** [jdeal/doctor#16]
Is there currently a technique to document functions (callbacks, for instance) passed as argument ?

``` js
/**
 * getJSON
 * 
 * @param  {String}   query - blah
 * @param  {Function} callback - executed when data are returned (documentation ?)
 * @return {Object} this
 */
var getJSON = function(query, callback) {
};
```

I think it's an important feature, since JS is full of these complex argumented callbacks functions. If this feature doesn't exist in doctor, I'd be happy to discuss the syntax with you and try an implementation !

Some syntax proposals I found :
http://code.google.com/p/jsdoc-toolkit/issues/detail?id=319
https://developers.google.com/closure/compiler/docs/js-for-compiler#types
https://groups.google.com/forum/?fromgroups=#!msg/jsdoc-users/03PTdjapZ3U/YamE0pVHR9MJ

**Comment by jdeal** [comment]
Sorry for the sloooow reply. I just pushed/published support for this. I went with:

``` js
/**
 * getJSON
 * 
 * @param  {String}   query - blah
 * @param  {Function(err, foo)} callback - executed when data are returned
 * @return {Object} this
 */
var getJSON = function(query, callback) {
};
```

In the report, in the types array for the parameter, the type will be an object instead of a string if it has parameters. The object will have the type name (Function, in the above example) and the parameters. The default doctor view now just spits out the parameters as part of the type name.
