### ISSUE TITLE
generating docs for express

### ISSUE THREAD

**Issue by defunctzombie** [jdeal/doctor#19]
I tried the basic cli for generating docs for expressjs from the package.json file however this yielded no useful output. I used the default view and reporters. The output files were generated but contained no info.

Any suggestions? Do I need to enable specific grammars, etc?

**Comment by jdeal** [comment]
It looks like TJ is doing two things doctor doesn't like.

First, and worst, in index.js, he's got this:

``` js
module.exports = process.env.EXPRESS_COV
  ? require('./lib-cov/express')
  : require('./lib/express');
```

Second, in lib/express.js, he's exporting a function (createApplication) that hasn't yet been defined.

The second problem will be a pain to fix, but it's certainly doable. I knew this was a problem but just hadn't prioritized fixing it.

The first problem can only be fixed by allowing you to inform doctor which path to take. Again, this is doable, but it's a pretty big can of worms. I certainly knew this was a problem, but I had no plans of fixing it. Is part of your use case documenting third-party modules, or were you just playing around and happened to first grab express?

Note that if you remove the conditional from express and move the function, you get documentation for exactly one function: createApplication. That's expected, since that's the only thing it exports. It would be nice if doctor followed return values and documented those. That's also complicated, especially in this case, since express is actually exporting the return value of a function from another third-party module, connect. For your own code, you can cheat by adding @public tags to indirectly-exported things that you want documented.

**Comment by defunctzombie** [comment]
I was just playing around with some various modules. I will move the
function and see what effect that has.

As for the requires, you could ignore ones you don't know about. Also, take
a look at
https://github.com/shtylman/node-required if you haven't already.

I have some more suggestions but I think I will make a separate issue for
those :)
