### ISSUE TITLE
How to programatically generate a report for one file

### ISSUE THREAD

**Issue by defunctzombie** [jdeal/doctor#20]
What would be the best way to generate a report for a single file without following requires, etc? Is there any sort of doc that describes what the report output looks like?

Instead of having the monolithic doctor object, I would like to be able to more selective use individual components. The smallest bit being: given a js file, generate a report for it.

**Comment by jdeal** [comment]
Oh yeah, duh, I didn't really document the report output. I should do that.

The command-line interface is just a wrapper around the examine function, so just like you can do this:

``` bash
doctor myfile1.js
```

with the command-line, you can do this programmatically:

``` js
doctor.examine({files: ['myfiles1.js']}, function (err, report) {
  // work with report here
});
```

However, I see now that `report` is a bit misleading. `reportMap` or `reportFiles` would be more accurate. Although the typical use-case is that one report is returned, the report renderer can just as well return multiple report files. For example, you could render the report as a bunch of markdown files. Or, you could split the report into one report per module. So, the `report` above will be an object like this:

``` js
{
  "report.json": {
    "items": {
      "root": {
        "type": "group",
        "items": [
          "modules"
        ],
        ...
      },
      "modules": {
        "type": "group",
        "items": [
          "foo"
        ],
        ...
      },
      "foo": {
        "type": "module",
        "name": "foo",
        "items": [
          "foo.bar"
        ],
        ...
      },
      "foo.bar": {
        "type": "function",
        "params": [
          ...
        ]
      }
    }
  }
}
```

The `report` object (like I said, misnamed) is just a map of file names to rendered output. Because the default renderer is just passing along the report object, you get one key "report.json" mapping to the report object. The report object (currently) has one key "items" which is a map of item keys to item objects. Using the default renderer, you might want to do something like:

``` js
doctor.examine({files: ['myfiles1.js']}, function (err, report) {
  report = report['report.json'];
  var items = report.items;
  // work with report items here
});
```

I might want to consider breaking the API and having the renderer be able to skip that outer layer when the render module is only rendering single files. The "items" key is also currently unnecessary, but I wanted to leave the option open to later add other properties if necessary.

There is always a "root" item that has a list of other items, and each of those items can have other items. In the example above, the root item has a modules item which is just a group. The modules item has a foo item which is a module. And the foo item has a bar item which is a function. The report object structure is purposefully generic to (hopefully) allow for many use-cases.

If you don't want to follow required modules, just use the follow option:

``` js
doctor.examine({files: ['myfiles1.js'], follow: false}, function (err, report) {
  report = report['report.json'];
  var items = report.items;
  // work with report items here
});
```
